### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Chain validation failed

### ISSUE THREAD

**Issue by edubarrlima** [gerencianet/gn-api-sdk-android#1]
Há previsão de correção?

br.com.gerencianet.gnsdksample W: javax.net.ssl.SSLHandshakeException: Chain validation failed
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
br.com.gerencianet.gnsdksample W:     at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:338)
br.com.gerencianet.gnsdksample W:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:123)
br.com.gerencianet.gnsdksample W:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:147)
br.com.gerencianet.gnsdksample W:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:108)
br.com.gerencianet.gnsdksample W:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
br.com.gerencianet.gnsdksample W:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:641)
br.com.gerencianet.gnsdksample W:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:576)
br.com.gerencianet.gnsdksample W:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:147)
br.com.gerencianet.gnsdksample W:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
br.com.gerencianet.gnsdksample W:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
br.com.gerencianet.gnsdksample W:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
br.com.gerencianet.gnsdksample W:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
br.com.gerencianet.gnsdksample W:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
br.com.gerencianet.gnsdksample W:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
br.com.gerencianet.gnsdksample W:     at java.lang.Thread.run(Thread.java:764)
br.com.gerencianet.gnsdksample W: Caused by: java.security.cert.CertificateException: Chain validation failed
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:707)
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:560)
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:605)
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
br.com.gerencianet.gnsdksample W:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
br.com.gerencianet.gnsdksample W:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
br.com.gerencianet.gnsdksample W:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)

**Comment by iigorpedroso** [comment]
Qual foi o contexto que gerou o erro informado?
Lançamos uma nova versão da SDK. 
Recomendo que você atualize e tente realizar novamente a tarefa que gerou este erro.
